# Generated by Django 3.1.3 on 2020-11-18 17:11

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201118_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_png',
            field=models.ImageField(blank=True, null=True, upload_to='png'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.upload_video),
        ),
    ]
